package librarymanagement;

import databaseconnection.BooksDB;
import databaseconnection.DBConnection;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import librarymanagement.classes.users.User;
import librarymanagement.datav.CheckUserCreds;
import net.proteanit.sql.DbUtils;
import librarymanagement.classes.Book;
/**
 *
 * @author Chad Jones and Joseph Lumpkin
 */

public class BrowserJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BrowserJFrame
     */

    //Loading the user class from the DB.
    public static User user = CheckUserCreds.user;
    
    public BrowserJFrame() {
        initComponents();
    }
    
    public static DefaultTableModel userTableModel(){
        int numberOfColumns = user.checkedOutBooks.size();
        Vector<String> columnNames = new Vector<String>();
        columnNames.addElement("Product Code");
        columnNames.addElement("Title");
        columnNames.addElement("Genre");
        columnNames.addElement("Author");

        Vector<Vector<String>> rows = new Vector<Vector<String>>();

        for(Book book : user.checkedOutBooks){
            Vector<String> newRow = new Vector<String>();
            String pid = ""+book.getProductCode();
            newRow.addElement(pid);
            newRow.addElement(book.getTitle());
            newRow.addElement(book.getGenre());
            newRow.addElement(book.getAuthor());
            rows.addElement(newRow);
        }
        DefaultTableModel userDTM = new DefaultTableModel(rows, columnNames);
        return userDTM;
    }
    
    public void Close() throws IOException, FileNotFoundException, SQLException{
        User.updateUser(user);
        this.setVisible(false);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        tabs = new javax.swing.JTabbedPane();
        panelUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        labelUsername = new javax.swing.JLabel();
        labelDisplayName = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        userRefreshBtn = new javax.swing.JButton();
        labelFirstName = new javax.swing.JLabel();
        labelDisplayFName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        labelDisplayLName = new javax.swing.JLabel();
        panelBooks = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonRec = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        bkReturnBtn = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Library Management");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        BrowserJFrame.userTable.setModel(userTableModel());
        jScrollPane1.setViewportView(userTable);

        labelUsername.setText("Username:");

        try{labelDisplayName.setText(user.getUsername());}
        catch(Exception e){System.out.println(e
            + "\n where username is displayed on the BrowserJFrame.");}

    returnBtn.setText("Return Books");
    returnBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            returnBtnActionPerformed(evt);
        }
    });

    userRefreshBtn.setText("Refresh");
    userRefreshBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            userRefreshBtnActionPerformed(evt);
        }
    });

    labelFirstName.setText("First Name:");

    try{labelDisplayFName.setText(user.getfName());}
    catch(Exception e){System.out.println(e + "\n where first name is displayed on the BrowserJFrame");}

    labelLastName.setText("Last Name:");

    try{labelDisplayLName.setText(user.getlName());}
    catch(Exception e){System.out.println(e + "\n where last name is displayed on the BrowserJFrame");}

    javax.swing.GroupLayout panelUserLayout = new javax.swing.GroupLayout(panelUser);
    panelUser.setLayout(panelUserLayout);
    panelUserLayout.setHorizontalGroup(
        panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelUserLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(labelUsername)
                .addComponent(returnBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDisplayName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userRefreshBtn)
                .addComponent(labelFirstName)
                .addComponent(labelLastName)
                .addComponent(labelDisplayLName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDisplayFName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(21, Short.MAX_VALUE))
    );
    panelUserLayout.setVerticalGroup(
        panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelUserLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUserLayout.createSequentialGroup()
                    .addComponent(labelFirstName)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(labelDisplayFName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(labelLastName)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(labelDisplayLName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(labelUsername)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(labelDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(userRefreshBtn)
                    .addGap(18, 18, 18)
                    .addComponent(returnBtn))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(30, Short.MAX_VALUE))
    );

    tabs.addTab("User", panelUser);

    try{
        String query = "SELECT * FROM Books";
        PreparedStatement myStmt = DBConnection.db.connection.prepareStatement(query);
        ResultSet rs = myStmt.executeQuery(query);
        BrowserJFrame.bookTable.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
        System.out.println(e);
        System.out.println();
    }
    jScrollPane2.setViewportView(bookTable);

    jLabel1.setText("Search by ID:");

    buttonAdd.setText("Add");
    buttonAdd.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonAddActionPerformed(evt);
        }
    });

    buttonEdit.setText("Edit");
    buttonEdit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonEditActionPerformed(evt);
        }
    });

    buttonRec.setText("Recommend");
    buttonRec.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonRecActionPerformed(evt);
        }
    });

    searchBtn.setText("Search");
    searchBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            searchBtnActionPerformed(evt);
        }
    });

    bkReturnBtn.setText("Refresh");
    bkReturnBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bkReturnBtnActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout panelBooksLayout = new javax.swing.GroupLayout(panelBooks);
    panelBooks.setLayout(panelBooksLayout);
    panelBooksLayout.setHorizontalGroup(
        panelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelBooksLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(panelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel1)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bkReturnBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    panelBooksLayout.setVerticalGroup(
        panelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelBooksLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBooksLayout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(searchBtn)
                    .addGap(18, 18, 18)
                    .addComponent(bkReturnBtn)
                    .addGap(23, 23, 23)
                    .addComponent(buttonAdd)
                    .addGap(18, 18, 18)
                    .addComponent(buttonEdit)
                    .addGap(18, 18, 18)
                    .addComponent(buttonRec)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
            .addContainerGap())
    );

    tabs.addTab("Books", panelBooks);

    tabs.setSelectedIndex(1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(tabs)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(tabs)
            .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        new addBooksJFrame().setVisible(true);
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        new editBooksJFrame().setVisible(true);
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRecActionPerformed
        new recommendJFrame().setVisible(true);
    }//GEN-LAST:event_buttonRecActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null, 
                    "Sorry, it appears the search text area is blank."
                    + "\nPlease try again.");
        }
        else{
            new searchConfirmJFrame().setVisible(true);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        new askIDJFrame().setVisible(true);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void bkReturnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkReturnBtnActionPerformed
        try {
            BooksDB.updateBooksTable();
        } catch (SQLException ex) {
            Logger.getLogger(BrowserJFrame.class.getName())
                    .log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BrowserJFrame.class.getName())
                    .log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BrowserJFrame.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bkReturnBtnActionPerformed

    private void userRefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRefreshBtnActionPerformed
        BrowserJFrame.userTable.setModel(userTableModel());
    }//GEN-LAST:event_userRefreshBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            User.updateUser(user);
        } catch (IOException ex) {
            Logger.getLogger(BrowserJFrame.class.getName())
                    .log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BrowserJFrame.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrowserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrowserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrowserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrowserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrowserJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkReturnBtn;
    public static javax.swing.JTable bookTable;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonRec;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelDisplayFName;
    private javax.swing.JLabel labelDisplayLName;
    private javax.swing.JLabel labelDisplayName;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel panelBooks;
    private javax.swing.JPanel panelUser;
    private javax.swing.JButton returnBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JButton userRefreshBtn;
    public static javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}